### ISSUE TITLE
How to unlock a json if locked (Mistakenly) ?

### ISSUE THREAD

**Issue by p32929** [azirbel/npoint#22]
Mistakenly locked a JSON now trying to edit it but seems no option to revert the change.

**Comment by azirbel** [comment]
Hi, sorry I didn't see this issue. Looks like it got lost in my emails.

This behavior is intentional, because locking the data or schema is a guarantee that the data/schema won't change and downstream consumers. So in n:point, we show a warning before locking.

People mistakenly lock bins from time to time; we're all human. Contact support@npoint.io and I'll help you out. To prevent abuse, my policy is to require a solid indication that you own the bin. This is easy for private bins (where I can verify the email) and goes case-by-case for public bins.
